# Generated by Django 4.1.3 on 2022-12-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_content", models.TextField()),
                ("comment_created_at", models.DateTimeField(auto_now_add=True)),
                ("comment_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Festival_Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("festival_title", models.CharField(default="", max_length=50)),
                ("festival_desc", models.TextField()),
                ("festival_address", models.CharField(max_length=50)),
                ("festival_region", models.CharField(max_length=50)),
                ("festival_date", models.CharField(max_length=50)),
                ("festival_image", models.CharField(max_length=100)),
                ("festival_price", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Join_Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_title", models.CharField(max_length=20)),
                ("join_count", models.IntegerField(default=0)),
                ("join_desc", models.TextField()),
                ("join_period", models.DateTimeField()),
                ("join_status", models.BooleanField(default=False)),
                ("join_created_at", models.DateTimeField(auto_now_add=True)),
                ("join_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
